# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SimplePhotoShare' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SimplePhotoShare
    pod "FlickrKit"
    pod "SDWebImage"
    pod "CLImageEditor"
    pod "RealmSwift"
    pod "MBProgressHUD"
  target 'SimplePhotoShareTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SimplePhotoShareUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
